---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-proxmox
  namespace: csi-proxmox
spec:
  interval: 2h
  chartRef:
    kind: OCIRepository
    name: proxmox-csi
  valuesFrom:
    - kind: ConfigMap
      name: proxmox-csi-values
