---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app proxmox-csi
  namespace: &namespace csi-proxmox
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 2h
  path: ./kubernetes/main/apps/csi-proxmox/proxmox-csi/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
