---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: proxmox-ccm
spec:
  interval: 1h
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/sergelogvinov/charts/proxmox-cloud-controller-manager
  ref:
    tag: 0.2.14
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-ccm
  namespace: csi-proxmox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: proxmox-ccm
  valuesFrom:
    - kind: ConfigMap
      name: proxmox-ccm-values
