---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./httproute.yaml
#  - ./scrapeconfig.yaml
