---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kosh-casa
spec:
  secretName: kosh-casa-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: kosh.casa
  dnsNames: ["kosh.casa", "*.kosh.casa"]
