---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kosh-casa-tls
spec:
  refreshInterval: 1m
  secretStoreRefs:
    - name: bitwarden
      kind: ClusterSecretStore
  selector:
    secret:
      name: kosh-casa-tls
  template:
    engineVersion: v2
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        remoteRef:
          remoteKey: kosh-casa-tls
