# yaml-language-server: $schema=https://raw.githubusercontent.com/siderolabs/talos/refs/heads/main/website/content/v1.10/schemas/config.schema.json
cluster:
  apiServer:
    certSANs:
      - ${cluster_endpoint_ip}
      - ${cluster_endpoint_hostname}
machine:
  kernel:
    modules:
      - name: zfs
  nodeLabels:
    topology.kubernetes.io/region: ${region}
    topology.kubernetes.io/zone: ${zone}
  kubelet:
    clusterDNS:
      - 169.254.2.53
      - ${dns_server}
    nodeIP:
      validSubnets:
        - ${proxmox_subnet}
  network:
    hostname: ${name}
    interfaces:
      - interface: dummy0
        addresses:
          - 169.254.2.53/32
  install:
    wipe: true
  features:
    rbac: true
    stableHostname: true
    apidCheckExtKeyUsage: true
