---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
  annotations:
    "secret.reloader.stakater.com/reload": "cloudflare-tunnel-secret"
spec:
  endpoints:
    - dnsName: external.kosh.casa
      recordType: CNAME
      targets: ["${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"]
