---
originRequest:
  originServerName: external.kosh.casa

ingress:
  - hostname: kosh.casa
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.kosh.casa"
    service: *svc
  - service: http_status:404
